### ISSUE TITLE
Combined Reload/Stop/Go button is lost when opening a new window

### ISSUE THREAD

**Issue by mrnhmath** [FranklinDM/Stratum#3]
Whenever a new window is opened, the stylized R/S/G button that appears when placed on the address bar right end is lost and looks like a normal button: ![2](https://user-images.githubusercontent.com/13562431/43617875-786f18e8-969b-11e8-99c4-70c8ccaca576.PNG)

Windows 7 - PM 28.0.0b5

**Comment by FranklinDM** [comment]
I cannot confirm this (I've tested with both a clean and used profile). Could you check if have an extension that modifies the style/behavior of the reload button?

**Comment by mrnhmath** [comment]
I don't have any extension that modifies UI elements, guess my profile is borked. Thank you!
